name: Deploy

on:
  push:
    branches: [deploymate]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CloudMate Production

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push — frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cca-client:${{ github.sha }}

      - name: Build and push — backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cca-server:${{ github.sha }}

      - name: Build and push — Ai-services
        uses: docker/build-push-action@v5
        with:
          context: ./Ai-servises
          file: ./Ai-servises/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cca-ai-service:${{ github.sha }}

      - name: Deploy to VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} -t "
            cd ~/codebase-chat-assistant &&
            MONGODB_URI='${{ secrets.MONGODB_URI }}' \
            JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            GOOGLE_API_KEY='${{ secrets.GOOGLE_API_KEY }}' \
            CLIENT_IMAGE='${{ secrets.DOCKERHUB_USERNAME }}/cca-client:${{ github.sha }}' \
            SERVER_IMAGE='${{ secrets.DOCKERHUB_USERNAME }}/cca-server:${{ github.sha }}' \
            AI_SERVICE_IMAGE='${{ secrets.DOCKERHUB_USERNAME }}/cca-ai-service:${{ github.sha }}' \
            docker compose up -d --pull always --remove-orphans
          "
